version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dock-graphql
    container_name: web
    environment:
      MONGODB_URI: mongo:27017
      REDIS_URL: redis:6379
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=web'
      - 'traefik.frontend.rule=Host:localhost'
      - 'traefik.port=3000'

  mongo:
    image: mongo
    container_name: mongo

  redis:
    image: redis:alpine
    container_name: redis

  traefik:
    image: traefik:1.6
    container_name: traefik
    command:
      - '--api'
      - '--entrypoints=Name:http Address::80 Redirect.EntryPoint:https'
      - '--entrypoints=Name:https Address::443 TLS'
      - '--defaultentrypoints=http,https'
      - '--docker'
      - '--docker.domain=localhost'
      - '--docker.watch'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8080:8080
