version: '3.6'

services:
  koa:
    build:
      context: .
      dockerfile: Dockerfile
    image: koa-dock
    container_name: koa
    labels:
      - "traefik.enable=true"
      - "traefik.backend=koa"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=3000"

  traefik:
    image: traefik:1.6
    container_name: traefik
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.domain=localhost"
      - "--docker.watch"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8080:8080
