version: '3.6'

networks:
  gateway:
    driver: overlay
    external: true
  traefik:
    driver: overlay

services:
  web:
    image: michaeltobia/dock-graphql
    networks:
      - traefik
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - 'traefik.enable=true'
        - 'traefik.backend=web'
        - 'traefik.docker.network=traefik'
        - 'traefik.frontend.rule=Host:localhost'
        - 'traefik.port=3000'

  traefik:
    image: traefik:1.6
    command:
      - '--api'
      - '--entrypoints=Name:http Address::80 Redirect.EntryPoint:https'
      - '--entrypoints=Name:https Address::443 TLS'
      - '--defaultentrypoints=http,https'
      # WHEN YOU'RE READY TO DEPLOY
      # - "--acme"
      # - "--acme.storage=acme.json"
      # - "--acme.entryPoint=https"
      # - "--acme.httpChallenge.entryPoint=http"
      # - "--acme.onHostRule=true"
      # - "--acme.email=inquiry@localhost"
      - '--docker'
      - '--docker.swarmMode'
      - '--docker.domain=localhost'
      - '--docker.watch'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json
    networks:
      - gateway
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
